[package]
name = "git-but-better"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gbb"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
